#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@192.168.9.42"

if [[ "$*" == "$SSH mkdir -p /tmp" ]]; then
    exit 0
elif [[ "$*" == "$SSH chmod +x /tmp/foo" ]]; then
    exit 0
elif [[ "$*" == "$SSH rm -rf /tmp/foo" ]]; then
    exit 0
elif [[ "$*" == "$SSH /tmp/foo lol wut" ]]; then
    exit 0
else
    exit 1
fi
