#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@192.168.9.42"

if [[ "$*" == "$SSH exit 0" ]]; then
    exit 0
elif [[ "$*" == "$SSH mkdir --parents \$(dirname /root/foo)" ]]; then
    exit 0
elif [[ "$*" == "$SSH tee /root/foo" ]] && [[ $(cat) == "test" ]]; then
    exit 0
else
    exit 1
fi
