#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.210.0.13"

if [[ "$*" == "$SSH exit 0" ]]; then
    exit 0
elif [[ "$*" == "$SSH qemu-img snapshot -droot /mima/zero-sda.qcow2" ]]; then
    exit 0
elif [[ "$*" == "$SSH qemu-img snapshot -droot /mima/zero-sdb.qcow2" ]]; then
    exit 0
else
    exit 1
fi

