#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.210.0.13"

if [[ "$*" == "$SSH test -e /mima/zero-sda.qcow2" ]]; then
    exit 1
elif [[ "$*" == "$SSH mkdir --mode 0755 -p /mima" ]]; then
    exit 0
elif [[ "$*" == "$SSH qemu-img create -q -fqcow2 -olazy_refcounts=on -opreallocation=metadata /mima/zero-sda.qcow2 20G" ]]; then
    echo "qemu-img: Could not open '/mima/zero-sda.qcow2': Failed to get \"write\" lock"
    echo "Is another process using the image [/mima/zero-sda.qcow2]?"
    exit 1
else
    exit 1
fi
