#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.210.0.13"

if [[ "$*" == "$SSH qemu-img info --force-share --output=json /mima/zero-sda.qcow2" ]]; then
    echo 'foobar'
    exit 0
else
    exit 1
fi
