#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.210.0.13"

if [[ "$*" == "$SSH pgrep --full --pidfile /tmp/beta.pid qemu" ]]; then
    exit 1
elif [[ "$*" == "$SSH pgrep --full --pidfile /tmp/zero.pid qemu" ]]; then
    exit 0
else
    exit 1
fi
