#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=1 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.210.0.13"

if [[ "$*" == "$SSH exit 0" ]]; then
    exit 0
elif [[ "$*" == "$SSH test -e /tmp/zero.pid" ]]; then
    exit 0
elif [[ "$*" == "$SSH test -e /tmp/zero.socket" ]]; then
    exit 0
elif [[ "$*" == "$SSH pgrep --full --pidfile /tmp/zero.pid qemu" ]]; then
    exit 0
else
    exit 1
fi
