#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@192.168.9.42"

if [[ "$*" == "$SSH bash" ]]; then
    input=$(cat)
    if [[ "$input" == "test" ]]; then
      echo 'result'
      exit 0
    else
      exit 1
    fi
else
    exit 1
fi
