#! /usr/bin/env bash

readonly SSH1="-o BatchMode=yes -o ConnectTimeout=1 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@192.168.9.42"
readonly SSH2="-o BatchMode=yes -o ConnectTimeout=2 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@192.168.9.42"

if [[ "$*" == "$SSH1 exit 0" ]]; then
    echo 'foobar'
    exit 1
elif [[ "$*" == "$SSH2 exit 0" ]]; then
    exit 0
elif [[ "$*" == "$SSH2 mkdir -p /root/mima" ]]; then
    exit 0
elif [[ "$*" == "$SSH2 chmod +x /root/mima/foo" ]]; then
    exit 0
elif [[ "$*" == "$SSH2 /root/mima/foo" ]]; then
    exit 0
else
    exit 1
fi
