#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.210.0.13"

if [[ "$*" == "$SSH test -e /mima/zero-sda.qcow2" ]]; then
    exit 0
elif [[ "$*" == "$SSH test -e /mima/zero-sdb.qcow2" ]]; then
    exit 1
elif [[ "$*" == "$SSH mkdir --mode 0755 -p /mima" ]]; then
    exit 0
elif [[ "$*" == "$SSH qemu-img create -q -fqcow2 -olazy_refcounts=on -opreallocation=metadata /mima/zero-sdb.qcow2 100G" ]]; then
    exit 0
elif [[ "$*" == "$SSH qemu-img snapshot -croot /mima/zero-sdb.qcow2" ]]; then
    exit 0
else
    exit 1
fi
