#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.210.0.13"

if [[ "$*" == "$SSH mkdir --mode 0755 -p /tmp" ]]; then
    exit 0
elif [[ "$*" == "$SSH qemu-system-x86_64 -name zero -machine q35,accel=kvm -cpu host -m 8192M -smp 2 -no-user-config -nodefaults -daemonize -runas nobody -monitor unix:/tmp/zero.socket,server,nowait -pidfile /tmp/zero.pid -vga std -spice port=5901,disable-ticketing=on -object iothread,id=iothread1 -device virtio-scsi-pci-non-transitional,iothread=iothread1 -device scsi-cd,drive=drive.cd0 -drive if=none,id=drive.cd0,format=raw,media=cdrom,file=/mima/centos7.iso -device scsi-cd,drive=drive.cd1 -drive if=none,id=drive.cd1,format=raw,media=cdrom,file=/mima/zero-ks.iso" ]]; then
    exit 0
elif [[ "$*" == "$SSH chmod 644 /tmp/zero.pid" ]]; then
    exit 0
else
    exit 1
fi
