#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=1 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@10.210.0.13"

if [[ "$*" == "$SSH exit 0" ]]; then
    exit 0
elif [[ "$*" == "$SSH qemu-img info --force-share --output=json /mima/zero-sda.qcow2" ]]; then
    echo "qemu-img: Could not open /mima/zero-sda.qcow2: Could not open '/mima/zero-sda.qcow2': No such file or directory"
    exit 1
else
    exit 1
fi
