#! /usr/bin/env bash

readonly SSH="-o BatchMode=yes -o ConnectTimeout=10 -o ForwardAgent=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@192.168.9.42"

if [[ "$*" == "$SSH mkdir -p /root/mima" ]]; then
    echo 'foobar'
    exit 1
else
    exit 1
fi
